### ISSUE TITLE
Use SecureString in Run Command

### ISSUE THREAD

**Issue by davidobrien1985** [awsdocs/aws-systems-manager-user-guide#104]
In step 13 of https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-console.html
Is it possible to reference a `SecureString` in here?

**Comment by JimbroAmazon** [comment]
Hi David, My apologies for the delayed response to your question. Yes, absolutely, you can choose SecureString for that walkthrough. While working through the procedure, if you choose SecureString, the KMS Key ID field appears. If you don't provide a KMS customer master key (CMK) ID, a CMK ARN, an alias name, or an alias ARN, then the system uses alias/aws/ssm, which is the AWS managed CMK for Systems Manager. If you don't want to use this key, then you can use a customer managed CMK. For more information about SecureString parameters, see SecureString parameters (https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-securestring.html). Thanks!

**Comment by VladimirDrozdenko** [comment]
I think the question that David was asking was: "is it possible to pass a parameter to the document that references a SecureString?" and if this is the question the answer is **no**.
If you follow the documentation (step 13) the command parameter 

> echo {{ssm:parameter-name}}

parameter-name cannot be of type SecureString. If you want to pass a value of a SecureString to your document, the recommended security practice is to resolve parameter value on the instance. Therefore, you'll have to access Parameter Store API directly from your script.

Example:
> export MY_SECRET=`aws ssm get-parameter --name my-secret-parameter --with-decryption | jq '.Parameter.Value'`
