### ISSUE TITLE
Updating Windows2

### ISSUE THREAD

**Issue by nbelley** [awsdocs/aws-systems-manager-user-guide#123]
Steps  are going fine until:

`72a89bf1-d40e-4d3e-80ad-2dce052f71cb | 1 | putSSMInvocationMetric | aws:putServerUpgradeMetrics | Success | Wed, 09 Sep 2020 17:48:02 GMT | Wed, 09 Sep 2020 17:48:03 GMT
-- | -- | -- | -- | -- | -- | --
c51af971-ecd5-46aa-becb-306116e2320d | 2 | describeOriginalInstanceDetails | aws:executeAwsApi | Success | Wed, 09 Sep 2020 17:48:03 GMT | Wed, 09 Sep 2020 17:48:04 GMT
bab6dba7-9a4a-4873-a167-9903b54f26fb | 3 | assertRootVolumeIsEbs | aws:assertAwsResourceProperty | Success | Wed, 09 Sep 2020 17:48:04 GMT | Wed, 09 Sep 2020 17:48:05 GMT
5da12f2a-4d2a-4bb8-8c1e-0a99576d776e | 4 | assertSubnetHasAutoAssignIPV4 | aws:assertAwsResourceProperty | Success | Wed, 09 Sep 2020 17:48:05 GMT | Wed, 09 Sep 2020 17:48:06 GMT
1a6e655d-d725-462f-82f7-d8fa93a2b507 | 5 | getOSVersion | aws:runCommand | Success | Wed, 09 Sep 2020 17:48:06 GMT | Wed, 09 Sep 2020 17:48:10 GMT
5ed4a580-c689-4bfc-a16a-e6b1348baf14 | 6 | branchUpgradePath | aws:branch | Success | Wed, 09 Sep 2020 17:48:10 GMT | Wed, 09 Sep 2020 17:48:11 GMT
c259abd1-ea25-4ebe-922f-fb3e6e58a9da | 7 | runUpgradeFrom2012R2Or2016 | aws:executeAutomation | Failed | Wed, 09 Sep 2020 17:48:11 GMT | Wed, 09 Sep 2020 20:43:00 GMT
7a7fc3ac-8263-4b6e-ae69-15e873899437 | 8 | putWindowsUpgradeFailureMetricFrom2012R2Or2016 | aws:putServerUpgradeMetrics | Success | Wed, 09 Sep 2020 20:43:00 GMT | Wed, 09 Sep 2020 20:43:00 GMT
`

**Comment by nbelley** [comment]
Is there a way to have some log of what hapened?

**Comment by CalebAWS** [comment]
Hello Nicolas, you can find information regarding how to troubleshoot failed automations in the reference below[1]. If you need further assistance in determining why a step failed while running an automation, I'd recommend contacting AWS Support at your convenience.

References:
[1] https://docs.aws.amazon.com/en_us/systems-manager/latest/userguide/automation-troubleshooting.html#automation-trbl-exstrt

**Comment by nbelley** [comment]
Thanks Caleb, I already checked there and there is no informations about that step, sadly. It's weird that an important step as UPDATING THE OS has not log whatsoever... What's the best way to contact the support?

**Comment by CalebAWS** [comment]
No problem Nicolas, one way is to use the link [https://aws.amazon.com/contact-us/](here) under Technical Support.
