### ISSUE TITLE
AWS-managed document returns unexpected exit code

### ISSUE THREAD

**Issue by stekern** [awsdocs/aws-systems-manager-user-guide#129]
Not sure if this is the correct repository to raise this issue in, but I'll give it a try.

**Details**:
I am using the AWS-managed document `AWS-ConfigureAWSPackage` in State Manager to handle automatic installation and updates of `AWSCodeDeployAgent`. Installation works fine on a fresh instance, but a non-zero exit code is returned if an instance is already running the latest version, thus leading to a failed association.

**Issue**:
The Run Command fails due to a non-zero exit code if an instance is running the latest version of the CodeDeploy agent.

**Expected behavior**:
The Run Command should only return a non-zero exit code if an actual update failed -- not if the instance is running the latest version.

**Output of Run Command**:
```
Initiating AWSCodeDeployAgent 1.2.1 install

Plugin aws:runShellScript ResultStatus Failed

install output: Running sh install.sh

Checking Yum Package Manager...

Checking Ruby install...

Checking Installed Ruby Version...

Supported Ruby Version Found

Checking if codedeploy-agent is already present...

Existing CodeDeploy Agent Detected. Checking Version...

Installed Version Same as Package Version. Skipping Install...

----------ERROR-------

install errors: failed to run commands: exit status 1

Failed to install package; install status Failed
```

**Comment by mark-amzn** [comment]
@stekern - I'll create an internal issue for this and assign it to the Run Command service team. Thanks for letting us know about this. -Mark
