### ISSUE TITLE
AWS-ConfigureDocker document unexpectedly fails

### ISSUE THREAD

**Issue by stekern** [awsdocs/aws-systems-manager-user-guide#131]
**Details**:
I am using the AWS-managed document `AWS-ConfigureDocker` in State Manager to automatically install and update Docker.

**Issue**:
The Run Command fails when targeting a RHEL 7.5 instance that has Docker installed. Standard output and error is not very descriptive, and it's hard to tell what the issue really is.

**Expected behavior**:
The Run Command should succeed even though Docker is installed, or output a more descriptive error. If RHEL 7.5 is not supported by the document, the documentation should reflect that.

**Output of Run Command**:
```
Installing yum-utilsAdd docker repo

----------ERROR-------

Error running yum-config-manager: exit status 1
```

**Comment by JimbroAmazon** [comment]
Hi Erlend, thanks for sending us this information. I've reported your issue to the product team and asked them to reproduce your issue. I'll let you know what they discover. It might take a few days. Thanks! -Jim

**Comment by stekern** [comment]
Thanks Jim. On a related note, is this the correct forum to bring up issues such as these?

I also have a couple of side questions, if you don't mind (maybe worth of a separate issue?):
- Are the AWS-managed documents actively maintained and generally ready for public use, or is their primary function a convenience for EC2 or internal AWS operations? The documentation seem to imply that as long you meet the requirements (usually something along the lines of `This plugin is supported on Linux and Windows Server`), you're good to go. But I find it hard to find any documentation of the innards of these documents, and a couple of the documents I've used have some edge cases and hard-to-debug errors.
- Is there an easy way to view the code backing AWS-managed documents?

**Comment by JimbroAmazon** [comment]
Hi Erlend, this GitHub repo is (generally speaking) designated for Systems Manager documentation issues or updates. For high-priority issues, we can certainly create a ticket for the product team or send them questions. Unfortunately, we don't have enough writers to address all issues/questions that come our way. 

Regarding your document questions, all AWS-* documents were developed by the product team and are subsequently maintained by them. Systems Manager (SSM) includes dozens (hundreds?) of documents to perform all kinds of tasks across different kinds of AWS resources. The type of resource you can administer depends on the type of SSM document you choose. This topic provides a nice intro to the different types of SSM documents: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-ssm-docs.html. Regarding their requirements, that too depends on the type of document you choose. For example, if you choose to run an Automation document, then you need to ensure that your user/group/role has the appropriate IAM permissions to run the document and ensure that your AWS resource (e.g. EC2 instance) has been configured for Systems Manager (Steps 4 and 5 here are often overlooked by users: https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up.html. ) 

And regarding how to see the code of AWS-* documents, you can view the YAML/JSON of the document in the Systems Manager console: Documents page > choose a document > choose the Content tab. I hope that helps. Best wishes, -Jim

**Comment by stekern** [comment]
Any updates here? I suspect the issue may be related to https://github.com/docker/for-linux/issues/1111.

I managed to automatically install Docker on an EC2 instance running RHEL 7.9 by using the following user-data, but it would be convenient with some detailed error information from the `AWS-ConfigureDocker` document. As it currently stands, the document does not seem to be working at all for RHEL 7.

```bash
# Install Docker
yum update -y
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum-config-manager --setopt=docker-ce-stable.baseurl=https://download.docker.com/linux/centos/7/\\\$basearch/stable --save
yum makecache
yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm
yum install -y docker-ce docker-ce-cli containerd.io
systemctl start docker
```

**Comment by JimbroAmazon** [comment]
Hi Erlend, I reached out to the product team this morning and boosted the priority of the ticket I opened. I can see that a dev has now been assigned the ticket and is investigating. I'll let you know what I learn. Thanks!

**Comment by JimbroAmazon** [comment]
Hi Erlend, the dev was able to reproduce your issue. He forwarded the ticket to the team that will investigate the fix. Thanks.

**Comment by JimbroAmazon** [comment]
Hi Erlend, I finally got a response from a engineer. He says the following:


This document is on a deprecation path. So I would not recommend customers still use it as it will be going away.
That said, the logic this implements is fairly simple, it looks like this is calling 
yum-config-manager --add-repo https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo
And that command is hitting an issue on that instance.

You could also point them at this file, it shows exactly the commands that are executed for each os.
https://github.com/aws/amazon-ssm-agent/blob/mainline/agent/plugins/configurecontainers/linuxcontainerutil/linuxcontainerutil.go

**Comment by stekern** [comment]
Thanks for the update, Jim!

Is there an overview somewhere over other documents that are on the path to deprecation? It would be helpful if the documents described at https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-plugins.html would reflect current recommendations from AWS.

**Comment by JimbroAmazon** [comment]
Hi Erlend, I've reached out to our dev managers asking them to provide me with updates about which documents/plugins will be deprecated. We'll add this information to the docs as soon as we get it. Thanks!
