### ISSUE TITLE
Session-manager plugin version and release are not up to date

### ISSUE THREAD

**Issue by iamhsa** [awsdocs/aws-systems-manager-user-guide#145]
It seems to me that [Session Manager plugin latest version and release history](https://github.com/awsdocs/aws-systems-manager-user-guide/blob/main/doc_source/session-manager-working-with-install-plugin.md#plugin-version-history) is not up to date.

The last version indicated in the table is 1.2.30.0 while the version installed in my place is 1.2.54.0.

```sh
$ session-manager-plugin --version
1.2.54.0
```
Could you complete the history ?

**Comment by mark-amzn** [comment]
Thanks, @iamhsa. We'll take a look at this.

**Comment by mark-amzn** [comment]
Info for v1.2.54.0 has been added.
