### ISSUE TITLE
No guidance on date formatting for "--expiration-date" flag

### ISSUE THREAD

**Issue by inflatador** [awsdocs/aws-systems-manager-user-guide#146]
Hello AWS Docs team,

Just filing an issue, as there is no guidance on date formatting for the "aws ssm --expiration-date" cli action.
Looks like it uses epoch timestamps. Would you mind adding that to your documentation?

Thanks for your time!

**Comment by CalebAWS** [comment]
Hello,

The reference below might help.

https://docs.aws.amazon.com/en_us/systems-manager/latest/userguide/systems-manager-datetime-strings.html

**Comment by mark-amzn** [comment]
@inflatador - Also, as luck would have it, we added info about the `--expiration-date` format yesterday: https://docs.aws.amazon.com/en_us/systems-manager/latest/userguide/sysman-managed-instance-activation.html#create-managed-instance-activation-commandline

**Comment by mark-amzn** [comment]
Also clarified now at https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateActivation.html#systemsmanager-CreateActivation-request-ExpirationDate.
