### ISSUE TITLE
ec2windows no longer a valid public parameter

### ISSUE THREAD

**Issue by rileysea** [awsdocs/aws-systems-manager-user-guide#160]
ec2windows is listed as a service for the public parameters in the documentation. However, when running the command below, ec2windows is not present. Suggest updating the documentation to reflect the available options.

aws ssm get-parameters-by-path --path /aws/service/list

**Comment by CalebAWS** [comment]
Thanks @rileysea we'll review the available namespaces and make any needed updates.
