### ISSUE TITLE
SLES and SLES for SAP - amazon-ssm-agent

### ISSUE THREAD

**Issue by djrsatx** [awsdocs/aws-systems-manager-user-guide#172]
Please update the documentation. The amazon-ssm-agent is installed by default on new AMIs published by SUSE. SUSE pulls the latest agent and has added it to the Public Cloud Module for SLE 12 and 15. This can be validated by launching an instance and testing and running zypper info amazon-ssm-agent.

SUSE made this change to support the ECS Anywhere launch that requires amazon-ssm-agent.

**Comment by JimbroAmazon** [comment]
Confirmed. We'll get the docs updated. Thanks!

**Comment by JimbroAmazon** [comment]
@djrsatx Thanks again for submitting this information. I just published an update to the docs. You'll be able to see the update using the following link in about 2 hours: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-install-ssm-agent.html
