### ISSUE TITLE
Clarify using customer managed keys

### ISSUE THREAD

**Issue by stoft** [awsdocs/aws-systems-manager-user-guide#179]
This sentence at the end of [line 20](https://github.com/awsdocs/aws-systems-manager-user-guide/blob/2806c5f4824f72d255ce32e1ecb1d9ae3ec4805a/doc_source/security-best-practices.md?plain=1#L20) confuses me since it, to me does not correlate with the previous information in the same paragraph:
> "You can't establish access control policies for these operations when you use the customer managed keys."

Is this actually referring to AWS managed keys?

**Comment by mark-amzn** [comment]
Yes, that should mention AWS managed keys instead. And we'll also note in the update AWS managed keys can be used, but only if the IAM policies of users who shouldn't access it for an operation explicitly deny access to the default key. For example: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html#ps-kms-permissions
