### ISSUE TITLE
document will try to patch an AMI or Volume if it has the same values on tags need to filter,run only on  AWS::EC2::Instance

### ISSUE THREAD

**Issue by witaloandrade** [awsdocs/aws-systems-manager-user-guide#187]
https://github.com/awsdocs/aws-systems-manager-user-guide/blob/2391b30c9149798c06acbf8596cc84353a4e05fd/doc_source/automation-authoring-runbooks-parent-child-example.md?plain=1#L812

document will try to patch an AMI or Volume if it has the same values on tags need to filter,run only on  AWS::EC2::Instance

{
    "AutomationExecution": {
        "AutomationExecutionId": "ab73c8e0-dd32-4298-b2b6-099b89685da0",
        "DocumentName": "parent",
        "DocumentVersion": "1",
        "ExecutionStartTime": "2022-06-10T15:06:19.052000-03:00",
        "ExecutionEndTime": "2022-06-10T15:06:50.626000-03:00",
        "AutomationExecutionStatus": "Failed",
        "StepExecutions": [
            {
                "StepName": "patchPrimaryTargets",
                "Action": "aws:executeAutomation",
                "TimeoutSeconds": 7200,
                "OnFailure": "Abort",
                "ExecutionStartTime": "2022-06-10T15:06:19.456000-03:00",
                "ExecutionEndTime": "2022-06-10T15:06:50.554000-03:00",
                "StepStatus": "Failed",
                "Inputs": {
                    "DocumentName": "\"RunbookTutorialChildAutomation\"",
                    "TargetParameterName": "\"InstanceId\"",
                    "Targets": "[{\"key\":\"tag:Name\",\"values\":[\"nada\"]}]"
                },
                "Outputs": {
                    "ClientToken": [
                        "f5babd10-dff1-447c-a724-74c984ee69a6"
                    ],
                    "ExecutionId": [
                        "f5babd10-dff1-447c-a724-74c984ee69a6"
                    ],
                    "Status": [
                        "Failed"
                    ]
                },
                "FailureMessage": "Step fails when it is Execution complete: verified. Failed to run automation with executionId: f5babd10-dff1-447c-a724-74c984ee69a6 Failed : \n{Status=[Failed], ExecutionId=[f5babd10-dff1-447c-a724-74c984ee69a6]}. Please refer to Automation Service Troubleshooting Guide for more diagnosis details.",
                "FailureDetails": {
                    "FailureStage": "PostVerification",
                    "FailureType": "Verification",
                    "Details": {
                        "VerificationErrorMessage": [
                            "Failed to run automation with executionId: f5babd10-dff1-447c-a724-74c984ee69a6 Failed : \n{Status=[Failed], ExecutionId=[f5babd10-dff1-447c-a724-74c984ee69a6]}"
                        ]
                    }
                },
                "StepExecutionId": "a4848ee5-efda-402c-ac65-318681bbd132",
                "OverriddenParameters": {}
            },
            {
                "StepName": "patchSecondaryTargets",
                "Action": "aws:executeAutomation",
                "TimeoutSeconds": 7200,
                "OnFailure": "Abort",
                "StepStatus": "Pending",
                "Inputs": {},
                "StepExecutionId": "4fa838e1-71bc-40f9-ac96-ea29803d403c",
                "OverriddenParameters": {}
            }
        ],
        "StepExecutionsTruncated": false,
        "Parameters": {
            "AutomationAssumeRole": [
                ""
            ],
            "PatchGroupPrimaryKey": [
                "Name"
            ],
            "PatchGroupPrimaryValue": [
                "nada"
            ],
            "PatchGroupSecondaryKey": [
                "Name"
            ],
            "PatchGroupSecondaryValue": [
                "nada2"
            ]
        },
        "Outputs": {},
        "FailureMessage": "Step fails when it is Execution complete: verified. Failed to run automation with executionId: f5babd10-dff1-447c-a724-74c984ee69a6 Failed : \n{Status=[Failed], ExecutionId=[f5babd10-dff1-447c-a724-74c984ee69a6]}. Please refer to Automation Service Troubleshooting Guide for more diagnosis details.",
        "Mode": "Auto",
        "ExecutedBy": "arn:aws:iam::123456789:user/mack",
        "Targets": [],
        "ResolvedTargets": {
            "ParameterValues": [],
            "Truncated": false
        }
    }
}
(END)

{
    "AutomationExecution": {
        "AutomationExecutionId": "f5babd10-dff1-447c-a724-74c984ee69a6",
        "DocumentName": "RunbookTutorialChildAutomation",
        "DocumentVersion": "1",
        "ExecutionStartTime": "2022-06-10T15:06:19.731000-03:00",
        "ExecutionEndTime": "2022-06-10T15:06:50.106000-03:00",
        "AutomationExecutionStatus": "Failed",
        "StepExecutions": [
            {
                "StepName": "ami-0287a96845f798794",
                "Action": "aws:executeAutomation",
                "ExecutionStartTime": "2022-06-10T15:06:20.241000-03:00",
                "ExecutionEndTime": "2022-06-10T15:06:21.306000-03:00",
                "StepStatus": "Failed",
                "Inputs": {
                    "InstanceId": "ami-0287a96845f798794"
                },
                "Outputs": {},
                "FailureMessage": "Step fails when it is Execute/Cancelling action. An error occurred (InvalidInstanceID.Malformed) when calling the DescribeInstances operation: Invalid id: \"ami-0287a96845f798794\". Please refer to Automation Service Troubleshooting Guide for more diagnosis details.",
                "StepExecutionId": "2c43f965-e81b-4c40-a934-eeea10abab63"
            },
            {
                "StepName": "i-0004dd6379ac82505",
                "Action": "aws:executeAutomation",
                "ExecutionStartTime": "2022-06-10T15:06:20.481000-03:00",
                "ExecutionEndTime": "2022-06-10T15:06:49.627000-03:00",
                "StepStatus": "Success",
                "Inputs": {
                    "InstanceId": "i-0004dd6379ac82505"
                },
                "Outputs": {},
                "StepExecutionId": "e010c4ab-5a91-4d9e-83c2-ff6d88296d8b"
            }
        ],
        "StepExecutionsTruncated": false,
        "Parameters": {},
        "Outputs": {},
        "FailureMessage": "Step fails when it is Execute/Cancelling action. An error occurred (InvalidInstanceID.Malformed) when calling the DescribeInstances operation: Invalid id: \"ami-0287a96845f798794\". Please refer to Automation Service Troubleshooting Guide for more diagnosis details.",
        "Mode": "Auto",
        "ParentAutomationExecutionId": "ab73c8e0-dd32-4298-b2b6-099b89685da0",
        "ExecutedBy": "arn:aws:iam::123456789:user/mack",
        "TargetParameterName": "InstanceId",
        "Targets": [
            {
                "Key": "tag:Name",
                "Values": [
                    "nada"
                ]
            }
        ],
        "ResolvedTargets": {
            "ParameterValues": [
                "ami-0287a96845f798794",
                "i-0004dd6379ac82505"
            ],
            "Truncated": false
        },
        "MaxConcurrency": "10",
        "MaxErrors": "100%"
    }
}
(END)

**Comment by CalebAWS** [comment]
Hi @witaloandrade, thanks for taking the time to provide us with your feedback. `TargetType` is a property specified at the time of document creation not in the inputs for a Run Command.
