### ISSUE TITLE
Get-SSMCommandInvocation does not return instance IDs.

### ISSUE THREAD

**Issue by GaTechThomas** [awsdocs/aws-systems-manager-user-guide#188]
Get-SSMCommandInvocation does not return instance ID. This is particularly problematic when a command was sent to multiple machines. How do we know what instance a given command result occurred on?

**Comment by CalebAWS** [comment]
Hi @GaTechThomas, can you clarify the issue you're encountering? Get-SSMCommandInvocation calls the ListCommandInvocations API operation which includes an InstanceId in the response elements. (https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CommandInvocation.html#systemsmanager-Type-CommandInvocation-InstanceId)

**Comment by GaTechThomas** [comment]
I'll see if I can send a repro this weekend.
________________________________
