### ISSUE TITLE
Incorrect dependency in Automation Document

### ISSUE THREAD

**Issue by Snozzberries** [awsdocs/aws-systems-manager-user-guide#189]
Within step 8 for https://github.com/awsdocs/aws-systems-manager-user-guide/blob/main/doc_source/automation-document-builder.md

Currently this is shown as optional in the docs and the console. State Manager will through an error "Automation Association Parameters must have length greater than 0 and less than or equal to 200" when there is no input parameter specified.

**Comment by CalebAWS** [comment]
Hello @Snozzberries, could you elaborate on the issue you're encountering and where you're seeing this error returned? For example, are you referring to a custom runbook you're trying to use in a State Manager association? Automation has supported optional parameters for quite some time.

**Comment by Snozzberries** [comment]
This occurs when using State Manager to create an association with an Automation Document owned by the account (custom).

The error was thrown when choosing to Create Association after completing the form.

The solution was to add the following to the document:
```
parameters:
  Test:
    type: String
    default: Testing
```

In other words, I am experiencing Automation Documentations **require** at least one parameter to be used within a State Manager Association.

**Comment by CalebAWS** [comment]
Hi @Snozzberries, apologies for the delayed response. I was unable to reproduce the error you described. However, if the Automation runbook has no parameters defined this would be a problem as the `AutomationAssumeRole` parameter must be present for the State Manager service to start the runbook. 

This is called out in step 7 of the console procedure [Running automations with triggers using State Manager
](https://docs.aws.amazon.com/systems-manager/latest/userguide/automation-sm-target.html#automation-sm-target-console)

>You must specify a role ARN in the AutomationAssumeRole field. State Manager uses the assume role to call AWS services specified in the runbook and run Automation associations on your behalf.
