### ISSUE TITLE
Systems Manager Relationship Diagram

### ISSUE THREAD

**Issue by Snozzberries** [awsdocs/aws-systems-manager-user-guide#190]
A diagram to show the relationships between different SSM features could be valuable. This isn't perfect, but could be a starting point.

![image](https://user-images.githubusercontent.com/431932/178601633-a2c16b47-6166-404f-8a09-b141a254188a.png)

**Comment by JimbroAmazon** [comment]
Hi Michael,

Thank so much for taking the time to create this diagram! And sorry for the late reply! As we get our writing team back up to fully-staffed status, we'll be looking at different ways to improve the docs, including the use of more diagrams. We'll take another look at this diagram at that time. If we do decide to use it (or an approximation of it) you'll likely need to provide some kind of verbal agreement that we can use it free of charge (for legal purposes, you know). Thanks again! This is great! :D

**Comment by Snozzberries** [comment]
Happy to share and appreciate the response! Hope you can fill those roles too.

**Comment by mark-amzn** [comment]
@Snozzberries - I'm closing this issue for our year-end scrub, but I have transferred your suggestion to our internal backlog of tasks for 2023. Cheers!
