### ISSUE TITLE
Extra period after the below sentence.

### ISSUE THREAD

**Issue by jtele2** [awsdocs/aws-systems-manager-user-guide#201]
On the [AWS Systems Manager Patch Manager page](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-patch.html): 

> This includes supported versions of several operating systems, as listed in [Patch Manager prerequisites](https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-prerequisites.html)..

See the extra period above ^^

I know ya'll are hyper-perfectionists like me, so fix this! :)

**Comment by mark-amzn** [comment]
You seem to know us all too well, @jtele2. ;)  Thanks for pointing this out! The fix is in the pipeline.
