### ISSUE TITLE
Incorrect command to check status/start SSM agent on Amazon Linux 1

### ISSUE THREAD

**Issue by cathaloc** [awsdocs/aws-systems-manager-user-guide#202]
I noticed that there is a mismatch between the following two pages with regards to the commands for checking the SSM agent status and starting it.

| Page | Status check command | Start command | Correct? | 
|------|------------------------|-----------------|----------|
|  [AMIs with SSM Preinstalled](https://docs.aws.amazon.com/systems-manager/latest/userguide/ami-preinstalled-agent.html)       |     `sudo systemctl status amazon-ssm-agent`     |   `sudo systemctl start amazon-ssm-agent`    | ❌  |
|  [Checking SSM Agent Status...](https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent-status-and-restart.html)       |     `sudo status amazon-ssm-agent`     |    `sudo start amazon-ssm-agent`   | ✅  |

In my case, the second row of the table contained the correct command for checking the status of the agent. My understanding is that Amazon Linux 1 does not support `systemd`. Therefore the first page should be updated to match the second page.

**Comment by mark-amzn** [comment]
Thanks for catching that, @cathaloc. You are correct. We'll get that fixed soon.
