### ISSUE TITLE
Repeated details about Patch selection on AL2022 and AL2023

### ISSUE THREAD

**Issue by HarshavardhanG7697** [awsdocs/aws-systems-manager-user-guide#213]
Hello,

I am raising this issue with regard to the snippet in [the document](https://github.com/awsdocs/aws-systems-manager-user-guide/blob/main/doc_source/patch-manager-selecting-patches.md) here:

---
Amazon Linux 2023 (AL2023) instances initially contains the updates that were available in the version of AL2023 and the chosen AMI. By default, your AL2023 instance doesn't automatically receive additional critical and important security updates at launch. Instead, with the deterministic upgrades through versioned repositories feature in AL2023, which is turned on by default, you can apply updates based on a schedule that meets your specific needs. For more information, see [Deterministic upgrades through versioned repositories](https://docs.aws.amazon.com/linux/al2023/ug/deterministic-upgrades.html) in the Amazon Linux 2023 User Guide.

On Amazon Linux 2022, the preconfigured repositories are tied to locked versions of package updates. When new Amazon Machine Images (AMIs) for Amazon Linux 2022 are released, they are locked to a specific version. For patch updates, Patch Manager retrieves the latest locked version of the patch update repository and then updates packages on the managed node based on the content of that locked version.

On AL2023, the preconfigured repository is the following:

    Repo ID: amazonlinux

    Repo name: Amazon Linux 2023 repository

On Amazon Linux 2022 (preview release), the preconfigured repositories are tied to locked versions of package updates. When new Amazon Machine Images (AMIs) for Amazon Linux 2022 are released, they are locked to a specific version. For patch updates, Patch Manager retrieves the latest locked version of the patch update repository and then updates packages on the managed node based on the content of that locked version.

On Amazon Linux 2022, the preconfigured repository is the following:

    Repo ID: amazonlinux

    Repo name: Amazon Linux 2022 repository
---

I believe that the order is incorrect. Also, the information with regard to AL2022 and AL2022 (preview release) is same but has their own paragraph. I believe that the documentation should be as below. Please feel free to correct me if I have misunderstood this:

*suggested corrections*

---
Amazon Linux 2023 (AL2023) instances initially contains the updates that were available in the version of AL2023 and the chosen AMI. By default, your AL2023 instance doesn't automatically receive additional critical and important security updates at launch. Instead, with the deterministic upgrades through versioned repositories feature in AL2023, which is turned on by default, you can apply updates based on a schedule that meets your specific needs. For more information, see [Deterministic upgrades through versioned repositories](https://docs.aws.amazon.com/linux/al2023/ug/deterministic-upgrades.html) in the Amazon Linux 2023 User Guide.

On AL2023, the preconfigured repository is the following:

    Repo ID: amazonlinux

    Repo name: Amazon Linux 2023 repository

On Amazon Linux 2022 and Amazon Linux 2022 Preview Release, the preconfigured repositories are tied to locked versions of package updates. When new Amazon Machine Images (AMIs) for Amazon Linux 2022 are released, they are locked to a specific version. For patch updates, Patch Manager retrieves the latest locked version of the patch update repository and then updates packages on the managed node based on the content of that locked version.

On Amazon Linux 2022, the preconfigured repository is the following:

    Repo ID: amazonlinux

    Repo name: Amazon Linux 2022 repository
---

**Comment by ghost** [comment]
We are retiring AWS documentation on GitHub[1], but I have transferred this issue to our internal tracking system.

Thank you!

---

[1] https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/
