### ISSUE TITLE
Seeking Help Creating Systems Manager Automation Walkthroughs

### ISSUE THREAD

**Issue by JimbroAmazon** [awsdocs/aws-systems-manager-user-guide#30]
Hi All,

The Systems Manager documentation team is seeking help in drafting walkthroughs that help customers use Systems Manager Automation in different ways. Specifically, we are looking for help in drafting the following list of topics. If you have experience with Automation, and would be interested in drafting one or more of the following walkthroughs, please submit a pull request as explained in these directions: https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/CONTRIBUTING.md . You don’t have to be an exceptional writer. We simply need help creating real-world content. I will rewrite your content to make it conform to our writing style and guidelines. Thanks in advance for your help!! -Jim

Getting started with Automation 
  Executing runbooks step-by-step
  Executing an Automation that uses approvals
  Executing Automations based on triggers
     Invoking an Automation from a CloudWatch trigger
     Invoking an Automation from a Maintenance Window target
Authoring Automation documents
  Best practices for authoring Automation documents
  Authoring a simple “Hello World” Automation 
  Authoring complex Automations using actions
  Authoring rollbacks and cleanup in your SSM documents  from OnFailure conditions
  Authoring Automation documents that call other Automation documents (nested)
  Authoring Automation documents via GitHub 
Best practices and methodology for testing Automations
How to share Automations across AWS accounts
Patching instances by using Automation
Automation walkthroughs for common uses cases on AWS resources
  Automations for managing EC2 instances (Linux and Windows)
  Automations for managing snapshots
  Automations for working with RDS
Other (the sky is the limit here!)

Jim Brotherton
Amazon Web Services
Senior Technical Writer 
AWS Systems Manager

**Comment by alemartini** [comment]
Posted 2 PRs to help with this issue:

https://github.com/awsdocs/aws-systems-manager-user-guide/pull/31
https://github.com/awsdocs/aws-systems-manager-user-guide/pull/32

I am going to open a new issue to track example creations, IAM permissions and step descriptions for the AWS-* docs.
