### ISSUE TITLE
Add IAM permissions to AWS-* Automation documents

### ISSUE THREAD

**Issue by alemartini** [awsdocs/aws-systems-manager-user-guide#33]
Related to https://github.com/awsdocs/aws-systems-manager-user-guide/issues/30

AWS-* Automation documents do not currently explain what IAM permissions are needed to run them.
This issue is to track the work to add such information to every AWS-* Automation document.

An example of how this section should look like can be found here:

https://github.com/awsdocs/aws-systems-manager-user-guide/blob/master/doc_source/automation-awssupport-troubleshootssh.md#required-iam-permissions

**Comment by mark-amzn** [comment]
@alemartini - We have an internal ticket for this issue. Closing this one as a duplicate, and thank you for your contribution!
