### ISSUE TITLE
Add examples to AWS-* Automation documents

### ISSUE THREAD

**Issue by alemartini** [awsdocs/aws-systems-manager-user-guide#34]
Related to https://github.com/awsdocs/aws-systems-manager-user-guide/issues/30

AWS-* Automation documents do not currently show execution examples.
This issue is to track the work to add such information to every AWS-* Automation document.

An example of how this section should look like can be found here:

https://github.com/awsdocs/aws-systems-manager-user-guide/blob/master/doc_source/automation-awssupport-troubleshootssh.md#examples

**Comment by mark-amzn** [comment]
We have an internal ticket for this. Closing this issue as a duplicate.
