### ISSUE TITLE
sysman-patch-baseline-console.md - malformed yum configuration

### ISSUE THREAD

**Issue by rferris** [awsdocs/aws-systems-manager-user-guide#43]
sysman-patch-baseline-console.md Step 11 includes a malformed yum.conf sample. 
This should read:

```
[main]  
cachedir=/var/cache/yum/$basearch/$releasever
keepcache=0
debuglevel=2
```

**Comment by mark-amzn** [comment]
Thanks, @rferris. We made this correction after you pointed out the error some time back.
