### ISSUE TITLE
Usage of SecureString parameters in custom documents

### ISSUE THREAD

**Issue by vorkos** [awsdocs/aws-systems-manager-user-guide#55]
Hi, 
I can't make it work - I'm trying to use a secure string parameter from the Parameter Store.
`{
  "schemaVersion": "2.2",
  "description": " .",
  "parameters": {
    "securestring": {
      "type": "String",
      "description": "Path to the ssh key in ssm parameter store - ssm:path",
      "default": "{{ssm:/test/test}}"
    }
  },
  "mainSteps": [
    {
      "action": "aws:runShellScript",
      "name": "runShellScript",
      "inputs": {
        "runCommand": [
          "#!/bin/bash",
          "securestring='{{securestring}}'",
          "echo $securestring"
        ]      }     }   ] }`
This code works with String but not with SecureString parameter(default ssm KMS key). Could you please point me what I need to change to make it work? The error message said nothing.

**Comment by JimbroAmazon** [comment]
Hi Kostiantyn, I'm sorry that you're having trouble getting your secure string parameter code to work. I don't see any obvious problems from looking at your sample. I'll send this sample to the Parameter Store engineers and see if they have any suggestions. I hope to reply very soon. Best wishes, -Jim

**Comment by JimbroAmazon** [comment]
Hi Kostiantyn, the Parameter Store developer told me that we don't support SecureString parameters in SSM Documents. Parameters must use either String or StringList in SSM Documents. I will review our documentation to see if we state this information clearly. Again, I'm sorry for any trouble this might have caused you. Best wishes, -Jim

**Comment by vorkos** [comment]
Thank you, Jim.

**Comment by chrispaynter** [comment]
Hey @JimbroAmazon 

I just started to use custom documents for the first time, to replace the need to send SSH commands to EC2 directly from my build server.

Things have been going smoothly up until the point I went to inject my database connection string into one of the steps in the command. It kept failing. This thread tells me why.

It's a shame we can't use secure strings, it erodes a bit of the power of documents I feel.

What's the recommended approach if we want to use use our secured strings in commands?

Will I need to get my build server to grab the parameter first, and then send it manually to the command via the CLI? 

(the command is run via CLI anyway, but the extra step of grabbing the parameter manually feels redundant when you can reference the non secured parameters directly in the command. Not to mention it means I have to move a secret out of the AWS domain, onto my build server, only to then send it back to AWS again. A bit gross). 

Any advice would be appreciated.

**Comment by chrispaynter** [comment]
Disregard, the obvious alternative in my case is to call into the SSM parameter store directly from my script.
