### ISSUE TITLE
Steps to create json format of shell/powershell script

### ISSUE THREAD

**Issue by Suresh-TechM** [awsdocs/aws-systems-manager-user-guide#60]
In all the aws docs present for creating SSM document , there is only mention of using powershell.json or shellscript.json . What is the recommended way converting our normal powershell/shell scripts to json format so that we can use it in 
aws ssm create-document --content file:///home/ec2-user/RunShellScript.json  --name "RunShellScript" --document-type "Command"

**Comment by JimbroAmazon** [comment]
Hi Suresh-TechM, 
Thank you for your question. I will forward it to a few people in the engineering team to see if we do, in fact, have a recommended way  of converting powershell/shell scripts to json. In the meantime, you might also ask your question on the Systems Manager Forums: https://forums.aws.amazon.com/forum.jspa?forumID=185

Best wishes,
-Jim

**Comment by mark-amzn** [comment]
We don't have a recommended method for converting PowerShell/shell scripts to json. If you're still seeking input on the question, you might still try the Systems Manager forum: https://forums.aws.amazon.com/forum.jspa?forumID=185
