### ISSUE TITLE
amazon-ssm-agent.json

### ISSUE THREAD

**Issue by manuelh2410** [awsdocs/aws-systems-manager-user-guide#68]
No Guidelines on how to edit the "amazon-ssm-agent.json"  file 
Can you include information on how to edit this file ?  and what each option means

**Comment by JimbroAmazon** [comment]
Hi Manuel, after speaking with the product team about this, they recommend that users only edit that file with the help of Product Support. Editing that file can cause unwanted changes to your system and for this reason we don't publish documentation on how to edit that file. Thanks!
