### ISSUE TITLE
AWSEC2-CloneInstanceAndUpgradeWindows

### ISSUE THREAD

**Issue by manuelh2410** [awsdocs/aws-systems-manager-user-guide#72]
HI there seems to be an issue with the following SSM document . 
AWSEC2-CloneInstanceAndUpgradeWindows

The code references ,a variable which has never been declared (set)
the variable is  $tmpLocation . 

the error resulting from this is : 

Step fails when it is verifying the command has completed. Command 0ef6ed00-4fcb-4211-b836-f92a8151af89 returns unexpected invocation result: {Status=[Failed], ResponseCode=[1], Output=[All disk(s) are online! Current drives are C:\,D:\,E:\ olddrives C:\,D:\ , Currentdrives C:\,D:\,E:\, Newdrive E:\, setup location is E:\\\setup.exe 2019-06-25 10:43:05.754 About to download answer file to $tmpLocation Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: An unexpected error occurred on a receive." ----------ERROR------- failed to run commands: exit status 1], CommandId=[0ef6ed00-4fcb-4211-b836-f92a8151af89]}. Please refer to Automation Service Troubleshooting Guide for more diagnosis details. 

My workaround entails creating a new copy of the document with the following line included.

            "function ReplaceCulture-AutoattendFile\n",
            "$tmpLocation = $env:TEMP\n",

**Comment by mark-amzn** [comment]
Unable to duplicate with more recent versions of AWSEC2-CloneInstanceAndUpgradeWindows.
