### ISSUE TITLE
How to stop "AWSSupport-SetupIPMonitoringFromVPC"

### ISSUE THREAD

**Issue by bijujo** [awsdocs/aws-systems-manager-user-guide#76]
I created an automation using AWSSupport-SetupIPMonitoringFromVPC document and it executed upto step 28 (createCloudWatchDashboard). Now as I am done with the troubleshooting, how do I delete the resources created using this? I tried "aws ssm stop-automation-execution", but I see the instance still running.  Thanks.

**Comment by awserik** [comment]
Hi @bijujo , once you have finished troubleshooting with the Automation workflow AWSSupport-SetupIPMonitoringFromVPC, you can run the Automation document AWSSupport-TerminateIPMonitoringFromVPC to remove the resources created.  You will need to provide at a minimum the instance ID, subnet ID, and Automation execution ID for the Setup IP monitoring workflow.  I hope this helps!

We'll look into adding a note regarding this secondary document to the topic for [AWSSupport-SetupIPMonitoringFromVPC](https://docs.aws.amazon.com/systems-manager/latest/userguide/automation-aws-setupipmonitoringfromvpc.html). For more information on AWSSupport-TerminateIPMonitoringFromVPC, see the following topic:
https://docs.aws.amazon.com/systems-manager/latest/userguide/automation-awssupport-terminateipmonitoringfromvpc.html

**Comment by bijujo** [comment]
@awserik , Thank you very much. It worked for me.
