### ISSUE TITLE
No existing doc on the ApplicationConfiguration SSM Doc type

### ISSUE THREAD

**Issue by lktslionel** [awsdocs/aws-systems-manager-user-guide#86]
Any doc planned for the SSM document type `ApplicationConfiguration` and `...Schema`.

**Comment by JimbroAmazon** [comment]
Hi Lionel, 
Thank you for sending along this question. The ApplicationConfiguration and ApplicationConfigurationSchema doc types are a part of AWS AppConfig, which launched just before reInvent. The user guide is, by no means, complete. We have more content in the works. I hope that helps. Thanks.
AWS AppConfig in the AWS Systems Manager User Guide: https://docs.aws.amazon.com/systems-manager/latest/userguide/appconfig.html
