### ISSUE TITLE
Bad doc. in Step 8: Retrieving the Configuration

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [awsdocs/aws-systems-manager-user-guide#89]
https://docs.aws.amazon.com/systems-manager/latest/userguide/appconfig-retrieving-the-configuration.html refers to a `clientid` property, that should be `client-id`.

**Comment by JimbroAmazon** [comment]
Hi Paulo, thanks for submitting this feedback. We already have a fix for this issue in our docs. It will be published tomorrow. Thank you!
