### ISSUE TITLE
Syntax error in CLI command

### ISSUE THREAD

**Issue by greyestapps** [awsdocs/aws-systems-manager-user-guide#9]
Hi,

there is an [syntax error](https://github.com/awsdocs/aws-systems-manager-user-guide/blob/master/doc_source/sysman-state-targets.md) after 

> Create an association for a managed instance named "ws-0123456789012345"

`aws ssm create-association --name value --targets "Key=Instance Ids,Values=ws-0123456789"} --name AWS-UpdateSSMAgent --schedule "cron(0 0 2 ? * SUN *)"`

The parameter _name_ is written twice and value of _targets_ is not a valid JSON - opening curly bracket is missing.

**Comment by JimbroAmazon** [comment]
Good catch! Thank you so much!

**Comment by greyestapps** [comment]
I‘m going to apply for a job at AWS in a few weeks - maybe I should attach
this to my application XD! Just kidding (the attachment part)- have a nice
day!
Jim Brotherton <notifications@github.com> schrieb am Mo. 7. Mai 2018 um
18:08:

**Comment by JimbroAmazon** [comment]
Good luck with your job application! Study the Amazon Leadership Principles. We take them very seriously here! ;)

**Comment by JimbroAmazon** [comment]
Updated command is now live
