### ISSUE TITLE
Limited Parameters and Dynamic

### ISSUE THREAD

**Issue by DRC-TJensen** [awsdocs/aws-systems-manager-user-guide#90]
Is there a way to create a custom Parameter for when using this template? I am using the IAM_User_Inactive_90_days Rule in AWS config and tried out using this Remediation rule but I don't get a lot of helpful information in my Jira Ticket.  It would be nice if it showed who the remediation action ran on for the account that was past 90 days of inactivity?

**Comment by DRC-TJensen** [comment]
Sorry I am using the AWS-CreateJiraIssue and it looks like only these parameters are allowed?

https://docs.aws.amazon.com/systems-manager/latest/userguide/automation-aws-createjiraissue.html

**Comment by JimbroAmazon** [comment]
Hi, DRC-Tjensen,
Yes, you're right that the AWS-CreateJiraIssue document doesn't support a custom parameter option. However, if you are comfortable creating SSM documents you could create your own. The AWS-CrateJiraIssue invokes the following SSM automation plugins: 
Document Steps

aws:createStack - Create CloudFormation stack to create Lambda IAM role and function.

aws:invokeLambdaFunction - Invoke Lambda function to create the Jira issue

aws:deleteStack - Delete the CloudFormation stack created.

You could copy the document, add the custom parameter, and then create it as a new document in the Systems Manager document store.

**Comment by DRC-TJensen** [comment]
Okay I was thinking that also. I am wondering what the allowed API's parameters could be used besides the current ones. I will do some testing.  
Thanks
